### ISSUE TITLE
Errors with expo

### ISSUE THREAD

**Issue by dj0nes** [Giphy/giphy-react-native-sdk#32]
Hi, very new react-native dev here, seeing errors when using expo. Not sure if this sdk isn't intended to work with expo, but it seems like that would be a bit odd given it's the default setup track in the react native [docs](https://reactnative.dev/docs/environment-setup).

## steps to reproduce the errors
1. Initialize an app and install the sdk with the following:
```sh
npm install --global expo-cli # from rn expo quick start guide
expo init giphytest && cd giphytest
expo install @giphy/react-native-sdk # yarn install shows same errors below
yarn start
```
2. Edit the default app component to contain only the `GiphyDialog` example from [here](https://github.com/Giphy/giphy-react-native-sdk/blob/main/docs/api.md#example-1).
3. Open the app via expo android/web/iOS simulator and see the following errors

### android
`TypeError: null is not an object (evaluating '_GiphySDK.NativeGiphySDK.configure')`

### web (console output)
```
Compiled with warnings.
./node_modules/@giphy/react-native-sdk/lib/module/index.js
Attempted import error: 'GiphyContentRequest' is not exported from './native/types'.

./node_modules/@giphy/react-native-sdk/lib/module/native/GiphyVideoView.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.

./node_modules/@giphy/react-native-sdk/lib/module/native/GiphyMediaView.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.

./node_modules/@giphy/react-native-sdk/lib/module/native/GiphyGridView.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native'.
```

### iOS
`Invariant Violation: Native module cannot be null.`

**Comment by pshoniuk** [comment]
Hello @dj0nes, sorry for the delayed response.  

Giphy React Native SDK isn't currently compatible with Expo projects. It's because Expo's `managed` workflow doesn't allow React Native libraries that introduce their own native code.

But Expo projects can be updated to become compatible. You can learn more about how to do this here:
 - [Expo - Adding custom native code](https://docs.expo.dev/workflow/customizing)
 - [Expo - Using Third-Party Libraries](https://docs.expo.dev/workflow/using-libraries/#using-third-party-libraries)

**Comment by bryanltobing** [comment]
Do we have expo plugin for this package to support expo managed workflow?
