### ISSUE TITLE
Expo-av doesn't work with this package on Android

### ISSUE THREAD

**Issue by shaquillehinds** [Giphy/giphy-react-native-sdk#62]
## 🐛 Bug Report

Expo-av video and audio don't work at all if I install the giphy package.

## To Reproduce

1. In bare react-native install expo modules: npx install-expo-modules
2. Install this package and the package expo-av@10.2.1 
3. Try to render a video component from the expo-av package

## Expected behavior

Video should play 

## Actual Behavior

Video doesn't load

## Your Environment

- Giphy React Native SDK version: 1.7.0
- React Native version: 0.66.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Pixel 4 Simulator and actual android device

**Comment by pshoniuk** [comment]
Hey @shaquillehinds, thanks for reaching out.

The problem seems to be related to the version of ExoPlayer.
`Expo-av@10.2.1` uses `ExoPlayer@2.9.2`, and the Giphy RN SDK uses `ExoPlayer@2.16.0`. Unfortunately, we can't help in this matter because the ExoPlayer API between these versions is completely different. I recommend patching the Giphy RN SDK, not using ExoPlayer, and using some external video player for Giphy Clips. You can find more information about this way in [this thread](https://github.com/Giphy/giphy-react-native-sdk/issues/49).

**Comment by shaquillehinds** [comment]
Thanks for the timely response @pshoniuk, I was thinking it was the exoplayer installation as well but a couple things don't make sense to me. I installed react-native-video which uses ExoPlayer@2.13.2 and it works fine with expo-av's version running ExoPlayer@2.9.2. Both packages work fine if they are both installed and I use them separately. However, if I install the giphy sdk, react-native-video runs as it's supposed to but expo-av doesn't at all. Keep in mind that I only installed the giphy sdk and it is not used at all in the code base. So to summarize, react-native-video works with the giphy package and the expo-av package even though the exoplayer versions are different, however expo-av will not function at all if the giphy package is installed even if the the giphy package is never called/used in the code base.

**Comment by pshoniuk** [comment]
`react-native-video` can use the Android MediaPlayer instead of the ExoPlayer ([details](https://github.com/react-native-video/react-native-video#android-installation)). I think this is how it works in your case. You can run the `gradle app:dependencies` command from the android folder to check the current dependencies tree. If you need help, share the result of running this command with us. At the moment, I see the situation as follows: you use `react-native-video` with Android MediaPlayer, so it works with `@giphy/react-native-sdk` and `expo-av`. But `@giphy/react-native-sdk` does not work with `expo-av` because they both use different versions of ExoPlayer, and usually, libraries with different versions of ExoPlayer cannot co-exist.
